server:
  port: 81

###################################### MyBatis 配置######################################
mybatis:
  # 指定 mapper.xml 的位置
  mapper-locations: classpath:mybatis/mapper/*.xml
  #扫描实体类的位置,在此处指明扫描实体类的包，在 mapper.xml 中就可以不写实体类的全路径名
  type-aliases-package: com.euripidess.credit_management
  configuration:
    #默认开启驼峰命名法，可以不用设置该属性
    map-underscore-to-camel-case: true

################################################## JDBC 通用配置  ##########################################
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource     #连接池类型
    username: root                                                                   #数据库登陆用户名
    password: 123456                                                                  #数据库登陆密码
    url: jdbc:mysql://127.0.0.1:3306/credit_management
    #    url: jdbc:mysql://127.0.0.1:3306/credit_management?serverTimezone=GMT#数据库url
    driver-class-name: com.mysql.cj.jdbc.Driver   #数据库驱动

---
#使用---来区分多个spring文件

##################################################Redis配置##################################################
#spring:
#  redis:
#    host: 127.0.0.1
#    port: 6379  #Redis服务器连接端口
#    password:  #Redis服务器连接密码（默认为空）
#    timeout: 30000 #连接超时时间（毫秒）
#    lettuce: #高版本pool包含在lettuce里面
#      pool:
#        max-active: 8 #连接池最大连接数（使用负值表示没有限制）
#        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-idle: 8 #连接池中的最大空闲连接
#        min-idle: 0 #连接池中的最小空闲连接

---

#################################################thymeleaf配置##################################################
spring:
  mvc:
    static-path-pattern: static/**
  resources:
    static-locations: classpath:static/,classpath:view/static/

  #开始thymeleaf设置
  thymeleaf:
    #禁用模板缓存
    cache: false
    suffix: .html
    prefix: classpath:/templates/



